order_report_types = {
    "" : "GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING",
    "" : "GET_ORDER_REPORT_DATA_INVOICING",
    "" : "GET_ORDER_REPORT_DATA_TAX",
    "" : "GET_ORDER_REPORT_DATA_SHIPPING",
    "" : "GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING",
    "" : "GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING",
    "" : "GET_FLAT_FILE_ORDER_REPORT_DATA_TAX",
    "" : "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL",
    "datewise_orders_data_in_flat_file" : "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL",
    "datewise_archived_orders_data_in_flat_file" : "GET_FLAT_FILE_ARCHIVED_ORDERS_DATA_BY_ORDER_DATE",
    "" : "GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL",
    "" : "GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL",
    "" : "GET_FLAT_FILE_PENDING_ORDERS_DATA",
    "" : "GET_PENDING_ORDERS_DATA",
    "" : "GET_CONVERGED_FLAT_FILE_PENDING_ORDERS_DATA",
}


return_report_types = {
   "" : "GET_XML_RETURNS_DATA_BY_RETURN_DATE",
   "" : "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
   "" : "GET_XML_MFN_PRIME_RETURNS_REPORT",
   "" : "GET_CSV_MFN_PRIME_RETURNS_REPORT",
   "" : "GET_XML_MFN_SKU_RETURN_ATTRIBUTES_REPORT",
   "" : "GET_FLAT_FILE_MFN_SKU_RETURN_ATTRIBUTES_REPORT"
}
 