# Generated by Django 5.1.3 on 2024-12-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='account_name',
            field=models.CharField(default='seller', max_length=400, unique=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='platform',
            field=models.CharField(default='Ecom', max_length=200),
        ),
        migrations.AddField(
            model_name='configuration',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
    ]
